---
repos:
  - repo: local
    hooks:
      - id: gitleaks
        name: Detect hardcoded secrets
        description: Detect hardcoded secrets using Gitleaks
        entry: gitleaks git --pre-commit --redact --staged --verbose
        language: system
        pass_filenames: false
      - id: nixfmt
        name: Format Nix files
        description: Format Nix files using nixfmt
        entry: nixfmt
        language: system
        types: [nix]
